import {env} from 'process';
import axios from 'axios';
import {ipLocation} from './index.mjs';

/**
 * Create API doc for ipapi.
 * Generated by ChatGPT 4.0
 *
 * @author https://chat.openai.com/
 */
/**
 * @openapi
 * /ip-location:
 *   post:
 *     description: Get location data from client IP
 *     tags:
 *       - Location
 *     requestBody:
 *       description: Client IP information
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               clientIp:
 *                 type: string
 *                 example: "203.0.113.195"
 *     responses:
 *       200:
 *         description: Location data retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 ip:
 *                   type: string
 *                   example: "203.0.113.195"
 *                 city:
 *                   type: string
 *                   example: "Vancouver"
 *                 country_name:
 *                   type: string
 *                   example: "Canada"
 *                 timezone:
 *                   type: string
 *                   example: "America/Vancouver"
 *       400:
 *         description: Missing client IP
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: "Missing client IP"
 *                 ip:
 *                   type: string
 *                   nullable: true
 *                   example: null
 *                 city:
 *                   type: string
 *                   example: "Unknown"
 *                 country_name:
 *                   type: string
 *                   example: "Unknown"
 *                 timezone:
 *                   type: string
 *                   example: "Unavailable"
 */
ipLocation.post('/', async (req, res) => {
    const ip = req.body.clientIp;

    // Return early if no IP can be found
    if (!ip) {
        return res.status(400).json({
            ip: null,
            city: 'Unavailable',
            country_name: 'Unavailable',
            timezone: 'Unavailable',
            error: 'Missing client IP',
        });
    }

    try {
        // Fetch location data from ipapi using axios
        const response = await axios.get(`https://api.ipapi.com/api/${ip}`, {
            params: {access_key: env.IPAPI_KEY},
        });

        // Return formatted location data to the frotend
        res.json({
            ip,
            city: response.data.city || 'Unavailable',
            country_name: response.data.country_name || 'Unavailable',
            timezone: response.data.time_zone?.id || 'Unavailable',
        });

        // If errors occur, set the response elements to Unavailable in catch block
    } catch (error) {
        console.error('IP Location lookup failed:', error.message);
        res.json({
            ip,
            city: 'Unavailable',
            country_name: 'Unavailable',
            timezone: 'Unavailable',
        });
    }
});
