import axios from 'axios';
import {status} from 'http-status';
import {weather} from './index.mjs';

/**
 * Create openAPI doc.
 * Generated by Claude Sonnet 4.0
 *
 * @author https://claude.ai/
 */

/**
 * @openapi
 * /weather/uv-index:
 *   get:
 *     description: Get UV index data for specified coordinates
 *     tags:
 *       - Weather
 *     parameters:
 *       - in: query
 *         name: lat
 *         schema:
 *           type: number
 *         required: true
 *         description: Latitude coordinate
 *         example: 49.2827
 *       - in: query
 *         name: lon
 *         schema:
 *           type: number
 *         required: true
 *         description: Longitude coordinate
 *         example: -123.1207
 *     responses:
 *       200:
 *         description: UV index data retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 uvi:
 *                   type: number
 *                   example: 5.2
 *                   description: UV Index value (0-11+, where higher values indicate greater UV exposure risk)
 *       400:
 *         description: Bad request - missing required parameters
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: Latitude and Longitude required
 *       500:
 *         description: Server internal error - failed to fetch UV index data
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: Failed to fetch UV index
 */
weather.get('/uv-index', async (req, res) => {
    const {lat, lon} = req.query;
    if (!lat || !lon) {
        return res
            .status(status.BAD_REQUEST)
            .json({error: 'Latitude and Longitude required'});
    }

    try {
        const {OPENWEATHER_API_KEY} = process.env;
        const response = await axios.get(
            `https://api.openweathermap.org/data/3.0/onecall`,
            {
                params: {
                    lat,
                    lon,
                    exclude: 'minutely,hourly,daily,alerts',
                    appid: OPENWEATHER_API_KEY,
                },
            },
        );

        const uvi = response.data?.current?.uvi;
        return res.status(status.OK).json({uvi});
    } catch (err) {
        console.error('UV index fetch error:', err);
        return res.status(status.INTERNAL_SERVER_ERROR).json({
            error: 'Failed to fetch UV index',
        });
    }
});
