import axios from 'axios';
import {status} from 'http-status';
import {weather} from './index.mjs';

/**
 * Create openAPI doc.
 * Generated by Claude Sonnet 4.0
 *
 * @author https://claude.ai/
 */

/**
 * @openapi
 * /weather/get-aqi:
 *   get:
 *     description: Get air quality index data for specified coordinates
 *     tags:
 *       - Weather
 *     parameters:
 *       - in: query
 *         name: lat
 *         schema:
 *           type: number
 *         required: true
 *         description: Latitude coordinate
 *         example: 49.2827
 *       - in: query
 *         name: lon
 *         schema:
 *           type: number
 *         required: true
 *         description: Longitude coordinate
 *         example: -123.1207
 *     responses:
 *       200:
 *         description: Air quality data retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 coord:
 *                   type: object
 *                   properties:
 *                     lon:
 *                       type: number
 *                       example: -123.1207
 *                     lat:
 *                       type: number
 *                       example: 49.2827
 *                 list:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       main:
 *                         type: object
 *                         properties:
 *                           aqi:
 *                             type: integer
 *                             example: 2
 *                             description: Air Quality Index (1-5, where 1 is Good and 5 is Very Poor)
 *                       components:
 *                         type: object
 *                         description: Pollutant concentrations
 *                       dt:
 *                         type: integer
 *                         example: 1609459200
 *                         description: Date and time (Unix timestamp)
 *       400:
 *         description: Bad request - missing required parameters
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: Latitude and Longitude required
 *       500:
 *         description: Server internal error - failed to fetch air quality data
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 *                   example: Failed to fetch AQI
 */
weather.get('/air-quality', async (req, res) => {
    const {lat, lon} = req.query;
    if (!lat || !lon) {
        return res
            .status(status.BAD_REQUEST)
            .json({error: 'Latitude and Longitude required'});
    }

    try {
        const {OPENWEATHER_API_KEY} = process.env;
        const response = await axios.get(
            `https://api.openweathermap.org/data/2.5/air_pollution?lat=${lat}&lon=${lon}&appid=${OPENWEATHER_API_KEY}`,
        );
        return res.status(status.OK).json(response.data);
    } catch (error) {
        console.error('AQI fetch error:', error);
        return res.status(status.INTERNAL_SERVER_ERROR).json({
            error: 'Failed to fetch AQI',
        });
    }
});
