import {status} from 'http-status';
import {Goal} from '../../model/goal.mjs';
import {User} from '../../model/user.mjs';
import {goal} from './index.mjs';
/**
 * Create openAPI doc.
 * Generated by Claude Sonnet 4.0
 *
 * @author https://claude.ai/
 */

/**
 * @openapi
 * /goal/{id}/complete:
 *   post:
 *     description: Mark a goal as completed for the authenticated user
 *     tags:
 *       - Goal
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: Goal ID
 *         example: 507f1f77bcf86cd799439011
 *     responses:
 *       200:
 *         description: Goal completed successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 goalId:
 *                   type: string
 *                   example: 507f1f77bcf86cd799439011
 *       401:
 *         description: Unauthorized - user not logged in
 *       404:
 *         description: Goal not found
 *       500:
 *         description: Server internal error
 */
goal.post('/:id/complete', async (req, res) => {
    try {
        const userId = req.session?.user?.id;
        if (!userId) return res.sendStatus(status.UNAUTHORIZED);

        const foundGoal = await Goal.findById(req.params.id).populate('badge');
        if (!foundGoal) return res.sendStatus(status.NOT_FOUND);

        const user = await User.findById(userId);
        if (!user) return res.sendStatus(status.UNAUTHORIZED);

        // Update score
        user.score = (user.score || 0) + (foundGoal.scorePoints || 0);

        // Add badge if it exists and hasn't already been earned
        const badgeId = foundGoal.badge?._id?.toString();
        if (badgeId && !user.badges.some((b) => b.toString() === badgeId)) {
            user.badges.push(badgeId);
        }

        await user.save();

        // Mark goal as completed
        await Goal.findByIdAndUpdate(req.params.id, {completed: true});

        return res
            .status(status.OK)
            .json({success: true, goalId: foundGoal.id});
    } catch (e) {
        console.error('Error completing goal:', e);
        return res.sendStatus(status.INTERNAL_SERVER_ERROR);
    }
});
