name: Continuous deploy

on:
  push:

jobs:
  release-nightly:
    name: Release nightly
    permissions:
      contents: read
      packages: write
    uses: silver886/github-actions/.github/workflows/release-oci.yaml@master
    with:
      image_tags: '["${{ github.ref_name }}","${{ github.sha }}"]'

  release-dev:
    name: Release dev
    if: ${{ github.ref == 'refs/heads/dev' }}
    permissions:
      contents: read
      packages: write
    uses: silver886/github-actions/.github/workflows/release-oci.yaml@master
    with:
      image_tags: '["dev"]'

  deploy-dev:
    name: Deploy dev
    needs: release-dev
    uses: silver886/github-actions/.github/workflows/deploy-cloudflare-truenas.yaml@master
    with:
      uri: ${{ vars.URI }}
      client_id: ${{ vars.CLIENT_ID }}
      apps: ${{ vars.APPS_DEV }}
    secrets:
      client_secret: ${{ secrets.CLIENT_SECRET }}
      api_key: ${{ secrets.API_KEY }}

  release-latest:
    name: Release latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write
    uses: silver886/github-actions/.github/workflows/release-oci.yaml@master
    with:
      image_tags: '["latest"]'

  deploy-latest:
    name: Deploy latest
    needs: release-latest
    uses: silver886/github-actions/.github/workflows/deploy-cloudflare-truenas.yaml@master
    with:
      uri: ${{ vars.URI }}
      client_id: ${{ vars.CLIENT_ID }}
      apps: ${{ vars.APPS }}
    secrets:
      client_secret: ${{ secrets.CLIENT_SECRET }}
      api_key: ${{ secrets.API_KEY }}
