name: Continuous deploy

on:
  push:

jobs:
  release-nightly:
    name: Release nightly
    permissions:
      contents: read
      packages: write
    uses: silver886/github-actions/.github/workflows/release-oci.yaml@master
    with:
      image_tags: '["${{ github.ref_name }}","${{ github.sha }}"]'

  release-latest:
    name: Release latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write
    uses: silver886/github-actions/.github/workflows/release-oci.yaml@master
    with:
      image_tags: '["latest"]'

  convert-secret:
    name: Convert secret
    runs-on: ubuntu-24.04
    needs: release-latest
    outputs:
      uri: ${{ steps.output.outputs.uri }}
      client_id: ${{ steps.output.outputs.client_id }}
      apps: ${{ steps.output.outputs.apps }}
    steps:
      - name: Output secret
        id: output
        shell: sh
        run: |
          echo 'uri=${{ secrets.URI }}' >> $GITHUB_OUTPUT
          echo 'client_id=${{ secrets.CLIENT_ID }}' >> $GITHUB_OUTPUT
          echo 'apps=${{ secrets.APPS }}' >> $GITHUB_OUTPUT

  deploy-latest:
    name: Release latest
    needs: convert-secret
    uses: silver886/github-actions/.github/workflows/deploy-cloudflare-truenas.yaml@master
    with:
      uri: ${{ needs.convert-secret.outputs.uri }}
      client_id: ${{ needs.convert-secret.outputs.client_id }}
      apps: ${{ needs.convert-secret.outputs.apps }}
    secrets:
      client_secret: ${{ secrets.CLIENT_SECRET }}
      api_key: ${{ secrets.API_KEY }}
